--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.567.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/07/2021 16:43:21
-- Server version: 10.3.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE samp_explorarsobreviver;

--
-- Drop table `changelog`
--
DROP TABLE IF EXISTS changelog;

--
-- Set default database
--
USE samp_explorarsobreviver;

--
-- Create table `changelog`
--
CREATE TABLE changelog (
  id int(11) NOT NULL AUTO_INCREMENT,
  date date DEFAULT current_timestamp,
  type enum ('feat', 'tweak', 'bugfix') NOT NULL,
  title varchar(32) NOT NULL,
  description varchar(128) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 24,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table changelog
--
INSERT INTO changelog VALUES
(1, '2021-07-19', 'tweak', 'Cama', 'Craft diferente'),
(2, '2021-07-19', 'tweak', 'Veículos', 'Stream de veículos mais eficiente'),
(3, '2021-07-19', 'bugfix', 'Deslog', 'Corrigo deslogar dentro de água'),
(4, '2021-07-19', 'tweak', 'Supply Drop', 'Mensagem simplificada'),
(5, '2021-07-19', 'feat', 'Inventário', 'Tecla ALT para abrir inventário dentro de um veículo'),
(6, '2021-07-19', 'tweak', 'Rádio', 'Removida tecla R para abrir Rádio no Veículo'),
(7, '2021-07-19', 'tweak', 'Veículos', 'Veículos nascem com menos gasolina e mais dano'),
(8, '2021-07-19', 'bugfix', 'Animações', 'Bugs de animação ao efetuar ações'),
(9, '2021-07-19', 'tweak', 'Sync/Mobile', 'Sincronização de animação melhorada para mobiles'),
(10, '2021-07-19', 'bugfix', 'Supply', 'Sinalização da Caixa de Suprimentos destruída na aterragem'),
(11, '2021-07-19', 'bugfix', 'Relógio', 'Removido temporariamente'),
(12, '2021-07-19', 'tweak', 'Morte', 'Ao morrer informa a causa da morte'),
(13, '2021-07-19', 'tweak', 'Inventário', 'Inventário mais rápido'),
(14, '2021-07-19', 'feat', 'Rádio', 'Côr verde para os jogadores na mesma rádio'),
(15, '2021-07-19', 'tweak', 'Textos', 'Mais correções de textos e traduções'),
(16, '2021-07-23', 'tweak', 'Itens', 'Remover item de inv/container mesmo tendo outro na mão'),
(17, '2021-07-23', 'bugfix', 'Tela', 'Tela escura no login corrigida'),
(18, '2021-07-23', 'bugfix', 'Veículo', 'Reparo de dano corrigido'),
(19, '2021-07-23', 'feat', 'Estrelas', 'Adicionado níveis de procurado. 1h vivo = 1 estrela'),
(20, '2021-07-23', 'tweak', 'Inventário', 'Design do inventário mais rápido'),
(21, '2021-07-23', 'bugfix', 'Munição', 'Corrigido bug de não aparecer munição'),
(22, '2021-07-23', 'feat', 'Defesas', 'Dono da defesa pode desmontala por ambos os lados'),
(23, '2021-07-23', 'feat', 'Item', 'Fragmento de Metal adicionado');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;