--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.636.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02/09/2021 16:52:09
-- Server version: 10.3.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE samp_explorarsobreviver;

--
-- Drop table `changelog`
--
DROP TABLE IF EXISTS changelog;

--
-- Set default database
--
USE samp_explorarsobreviver;

--
-- Create table `changelog`
--
CREATE TABLE changelog (
  id INT(11) NOT NULL AUTO_INCREMENT,
  date DATE DEFAULT current_timestamp,
  type ENUM('feat','tweak','bugfix') NOT NULL,
  title VARCHAR(32) NOT NULL,
  description VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 64,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table changelog
--
INSERT INTO changelog VALUES
(1, '2021-07-19', 'tweak', 'Cama', 'Craft diferente'),
(2, '2021-07-19', 'tweak', 'Veículos', 'Stream de veículos mais eficiente'),
(3, '2021-07-19', 'bugfix', 'Deslog', 'Corrigo deslogar dentro de água'),
(4, '2021-07-19', 'tweak', 'Supply Drop', 'Mensagem simplificada'),
(5, '2021-07-19', 'feat', 'Inventário', 'Tecla ALT para abrir inventário dentro de um veículo'),
(6, '2021-07-19', 'tweak', 'Rádio', 'Removida tecla R para abrir Rádio no Veículo'),
(7, '2021-07-19', 'tweak', 'Veículos', 'Veículos nascem com menos gasolina e mais dano'),
(8, '2021-07-19', 'bugfix', 'Animações', 'Bugs de animação ao efetuar ações'),
(9, '2021-07-19', 'tweak', 'Sync/Mobile', 'Sincronização de animação melhorada para mobiles'),
(10, '2021-07-19', 'bugfix', 'Supply', 'Sinalização da Caixa de Suprimentos destruída na aterragem'),
(11, '2021-07-19', 'bugfix', 'Relógio', 'Removido temporariamente'),
(12, '2021-07-19', 'tweak', 'Morte', 'Ao morrer informa a causa da morte'),
(13, '2021-07-19', 'tweak', 'Inventário', 'Inventário mais rápido'),
(14, '2021-07-19', 'feat', 'Rádio', 'Côr verde para os jogadores na mesma rádio'),
(15, '2021-07-19', 'tweak', 'Textos', 'Mais correções de textos e traduções'),
(16, '2021-07-23', 'tweak', 'Itens', 'Remover item de inv/container mesmo tendo outro na mão'),
(17, '2021-07-23', 'bugfix', 'Tela', 'Tela escura no login corrigida'),
(18, '2021-07-23', 'bugfix', 'Veículo', 'Reparo de dano corrigido'),
(19, '2021-07-23', 'feat', 'Estrelas', 'Adicionado níveis de procurado. 1h vivo = 1 estrela'),
(20, '2021-07-23', 'tweak', 'Inventário', 'Design do inventário mais rápido'),
(21, '2021-07-23', 'bugfix', 'Munição', 'Corrigido bug de não aparecer munição'),
(22, '2021-07-23', 'feat', 'Defesas', 'Dono da defesa pode desmontala por ambos os lados'),
(23, '2021-07-23', 'feat', 'Item', 'Fragmento de Metal adicionado'),
(24, '2021-07-25', 'tweak', 'Whitelist', 'ID de Discord completamente linkado com cada Conta'),
(25, '2021-08-06', 'tweak', 'Anti Cheat', 'Melhorado por um todo'),
(26, '2021-08-06', 'bugfix', 'Score', 'Contagem de horas vivo corrigido'),
(27, '2021-08-06', 'feat', 'Comando', 'Adicionado /novidades para ver estas mesmas novidades'),
(28, '2021-08-06', 'feat', 'Inventário', 'Tecla ALT GR agora abre o Inventário, estando dentro de um Veículo'),
(29, '2021-08-06', 'feat', 'Inventário', 'Prévisualização de Itens'),
(30, '2021-08-06', 'tweak', 'Inventário', 'Revisto, otimizado e melhorado'),
(31, '2021-08-06', 'bugfix', 'Itens', 'Agora pode pegar Itens perto de Porta-malas'),
(32, '2021-08-06', 'tweak', 'Lixeiras', 'Otimizado e com nova animação'),
(33, '2021-08-06', 'bugfix', 'Botão', 'Bug aleatório relacionado com os botões corrigido'),
(34, '2021-08-06', 'tweak', 'Inventário', 'Agora é chamado de Bolsos'),
(35, '2021-08-06', 'feat', 'Veículos', 'Mais 128 cores para os Veículos'),
(36, '2021-08-06', 'feat', 'Atendimento', 'Jogadores não poderão atacar jogadores que estão em atendimento com a Staff'),
(37, '2021-08-06', 'tweak', 'Anti-Cheat', 'Detetação de vida melhorado'),
(38, '2021-08-06', 'bugfix', 'Máquinas', 'Máquina de Sucata Voltou a funcionar'),
(39, '2021-08-06', 'tweak', 'Loot', 'Probabilidade para o Laser foi aumentada'),
(40, '2021-08-06', 'tweak', 'Loot', 'Adicionadas Placas'),
(41, '2021-08-06', 'feat', 'Itens', 'Relógio adicionado'),
(42, '2021-08-06', 'tweak', 'Loot', 'Respawn de Loot Otimizado no geral'),
(43, '2021-08-06', 'tweak', 'Loot', 'Agora quantos mais jogadores, mais itens nascem e vice-versa'),
(44, '2021-08-06', 'tweak', 'Texto', '"Pressione F para pegar" só aparecerá quando for possível pegar o item'),
(45, '2021-08-06', 'feat', 'Containers', 'Opção de Usar o item adicionada para containers'),
(46, '2021-08-06', 'feat', 'Chat', 'Agora você pode mencionar alguém no chat utilizando o nick, exemplo: Oi @kol, tudo bem? = Oi kolor4do, tudo bem?'),
(47, '2021-08-06', 'bugfix', 'Coldre', 'Agora funciona a 100%'),
(48, '2021-08-06', 'feat', 'Teleport', 'Adicionado locais de teleport, ou seja, botões que você pressiona e entra em um novo local'),
(49, '2021-08-06', 'tweak', 'Comida', 'Hotdog, pizza e Hamburguer não são mais comidas de cozinhar'),
(50, '2021-08-06', 'feat', 'Corpo', 'Agora você pode pegar o corpo de jogadores na mão'),
(51, '2021-08-06', 'tweak', 'Itens', 'Mochila Coração agora nasce com loot diferenciado de outras mochilas'),
(52, '2021-08-06', 'bugfix', 'Whitelist', 'Agora não pode mais executar comandos enquanto não tem sua conta vinculada (whitelist)'),
(53, '2021-08-08', 'bugfix', 'Ação', 'Barra de carregamento da gasolina corrigida'),
(54, '2021-08-08', 'feat', 'Discord', 'Poder ver chat Global e responder no <#874061189330665562>'),
(55, '2021-08-15', 'tweak', 'Bolso', 'Somente carona consegue abrir bolso no veiculo agora;'),
(56, '2021-08-15', 'bugfix', 'Itens', 'duplicados no tutorial corrigido;'),
(57, '2021-08-15', 'feat', 'Agora', 'é possivel abrir o porta-malas estando dentro do veículo como carona;'),
(58, '2021-08-15', 'feat', 'Comando', '/novidades adicionado;'),
(59, '2021-08-15', 'tweak', 'HUD', 'do veiculo na esquerda para mobile;'),
(60, '2021-08-15', 'bugfix', 'Alguns', 'crafts corrigidos;'),
(61, '2021-08-15', 'feat', 'Sistema', 'de VIP iniciado;'),
(62, '2021-08-15', 'feat', 'Chat', 'do server no discord e vice-versa;'),
(63, '2021-08-15', 'bugfix', 'Loot', 'por quantidade de jogadores online ajustado;');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;